# Generated by Django 3.1.7 on 2021-04-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prevHash', models.CharField(default=0, max_length=500)),
                ('data', models.CharField(default=0, max_length=100)),
                ('student_id', models.CharField(default=0, max_length=300)),
                ('first_name', models.CharField(default=0, max_length=300)),
                ('last_name', models.CharField(default=0, max_length=300)),
            ],
        ),
    ]
